entrypoint: "gunicorn -b :$PORT main:app"
env: flex
runtime: python
runtime_config: 
  python_version: 3
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 6
resources:
  memory_gb: 2.0
  disk_size_gb: 10